[build]
buildCommand = "npm install && npm run build"
watchPatterns = ["**"]

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma generate && npx tsx prisma/seed.ts && npm run start"
healthcheckPath = "/healthz"
healthcheckTimeout = 100