[build]
buildCommand = "npm install && npm run build"
watchPatterns = ["**"]

[deploy]
startCommand = "npx prisma migrate deploy && npx prisma generate && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100